### throw pushes up an exception (like break, return and continue)
### it will be passed up by most code expressions (TODO: arrays ?)
### the only way to catch and unwrap it is with the ! operator
### or the try ... catch construct.
### (x!) is equivalent to (try x catch e { e })

function unwrap_before_mult(x) {
    f1(x)! * 3
}

function unwrap_after_mult(x) {
    (f1(x) * 3)!
}

function try_catch(x) {
    try f1(x) * 3 catch y {
        y + 1
    }
}

function f1(x) {
    f2(x) * 5
}

function f2(x) {
    if x >= 10 {
        throw 10;
        @println("unreachable");
    } else {
        x
    }
}

@test("unwrap_before_mult(8)",120);
@test("unwrap_before_mult(10)",30);

@test("unwrap_after_mult(8)",120);
@test("unwrap_after_mult(10)",10);

@test("try_catch(8)",120);
@test("try_catch(10)",11);
