### throw pushes up an exception (like break, return and continue)
### it will be passed up by most code expressions (TODO: arrays ?)
### the only way to catch and unwrap it is with the ! operator

function unwrap_before_mult(x) {
    f1(x)! * 3
}

function unwrap_after_mult(x) {
    (f1(x) * 3)!
}

function f1(x) {
    f2(x) * 5
}

function f2(x) {
    if x >= 10 {
        throw 10;
        @println("unreachable");
    } else {
        x
    }
}

@test("unwrap_before_mult(8)",120);
@test("unwrap_before_mult(10)",30);

@test("unwrap_after_mult(8)",120);
@test("unwrap_after_mult(10)",10);
